awstockalert_form_configuration:
  path: /awstockalert/configuration
  methods: [GET, POST]
  defaults:
    _controller: 'Axelweb\AwStockAlert\Controller\AdminConfigurationController::index'
    # Needed to work with tab system
    _legacy_controller: AdminAwStockAlert
    _legacy_link: AdminAwStockAlert
