awmodulebase_form_configuration:
  path: /awmodulebase/configuration
  methods: [GET, POST]
  defaults:
    _controller: 'Axelweb\AwModuleBase\Controller\AdminConfigurationController::index'
    # Needed to work with tab system
    _legacy_controller: AdminAwModuleBase
    _legacy_link: AdminAwModuleBase
