services:
  _defaults:
    public: true

  # General form type
  axelweb.awstockalert.form.type.general:
    class: 'Axelweb\AwStockAlert\Form\GeneralFormType'
    parent: 'form.type.translatable.aware'
    public: true
    tags:
      - { name: form.type }

  axelweb.awstockalert.form.general_data_configuration:
    class: 'Axelweb\AwStockAlert\Form\GeneralDataConfiguration'
    arguments: ['@prestashop.adapter.legacy.configuration']

  axelweb.awstockalert.form.general_form_data_provider:
    class: 'Axelweb\AwStockAlert\Form\GeneralFormDataProvider'
    arguments:
      - '@axelweb.awstockalert.form.general_data_configuration'

  axelweb.awstockalert.form.general_form_data_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@axelweb.awstockalert.form.general_form_data_provider'
      - 'Axelweb\AwStockAlert\Form\GeneralFormType'
      - 'AwStockAlert'
